version: '3.3'  # You can downgrade from '3.8' to '3.3' if necessary.

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa_server
    environment:
      - DATABASE_URL=${DATABASE_URL}     # From environment variables or .env file
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
