version: '3.8'

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa_server
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Load from system environment
      NODE_ENV: development          # Load from system environment
      JWT_SECRET: ${JWT_SECRET}      # Load from system environment
      COOKIE_SECRET: ${COOKIE_SECRET} # Load from system environment
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
