version: '3.8'

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa_server
    environment:
      DATABASE_URL: postgres://postgres:admin321@host.docker.internal:5432/medusa-store  # Pointing to local PostgreSQL
      NODE_ENV: development
      JWT_SECRET: your_jwt_secret
      COOKIE_SECRET: your_cookie_secret
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
